"""auto-vote

Revision ID: d867d43daef6
Revises: 02d1f5d94532
Create Date: 2021-11-20 18:34:05.144566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd867d43daef6'
down_revision = '02d1f5d94532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes', sa.Column('user_id', sa.Integer(), nullable=False), sa.Column('post_id', sa.Integer(), nullable=False), sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
